class Food {
  final String id;
  final String name;
  final String description;
  final String category;
  final double price;
  final String image;
  final int calories;
  final double rating;
  final String cookingTime;

  Food({
    required this.id,
    required this.name,
    required this.description,
    required this.category,
    required this.price,
    required this.image,
    required this.calories,
    required this.rating,
    required this.cookingTime,
  });
}

// Data dummy makanan
final List<Food> foodList = [
  Food(
    id: '1',
    name: 'Nasi Goreng Spesial',
    description: 'Nasi goreng dengan telur, ayam, udang, dan sayuran segar. Disajikan dengan kerupuk dan acar.',
    category: 'Indonesian',
    price: 25000,
    image: '🍛',
    calories: 650,
    rating: 4.8,
    cookingTime: '15 menit',
  ),
  Food(
    id: '2',
    name: 'Sate Ayam',
    description: 'Sate ayam bakar dengan bumbu kacang khas, lontong, dan sambal. 10 tusuk per porsi.',
    category: 'Indonesian',
    price: 30000,
    image: '�串',
    calories: 450,
    rating: 4.9,
    cookingTime: '20 menit',
  ),
  Food(
    id: '3',
    name: 'Mie Ayam Bakso',
    description: 'Mie ayam dengan bakso sapi, pangsit goreng, dan sayuran. Kuah kaldu segar.',
    category: 'Indonesian',
    price: 20000,
    image: '🍜',
    calories: 550,
    rating: 4.7,
    cookingTime: '15 menit',
  ),
  Food(
    id: '4',
    name: 'Rendang Daging',
    description: 'Daging sapi rendang dengan bumbu rempah khas Padang. Empuk dan gurih.',
    category: 'Indonesian',
    price: 45000,
    image: '🍖',
    calories: 700,
    rating: 4.9,
    cookingTime: '120 menit',
  ),
  Food(
    id: '5',
    name: 'Gado-Gado',
    description: 'Sayuran segar dengan bumbu kacang, telur rebus, tahu, tempe, dan kerupuk.',
    category: 'Indonesian',
    price: 18000,
    image: '🥗',
    calories: 350,
    rating: 4.6,
    cookingTime: '10 menit',
  ),
  Food(
    id: '6',
    name: 'Sushi Salmon',
    description: 'Sushi salmon segar dengan nori, nasi, dan wasabi. 8 pieces per porsi.',
    category: 'Japanese',
    price: 50000,
    image: '🍣',
    calories: 400,
    rating: 4.8,
    cookingTime: '15 menit',
  ),
  Food(
    id: '7',
    name: 'Ramen Spicy',
    description: 'Ramen kuah pedas dengan telur, ayam, rumput laut, dan sayuran.',
    category: 'Japanese',
    price: 40000,
    image: '🍲',
    calories: 600,
    rating: 4.7,
    cookingTime: '20 menit',
  ),
  Food(
    id: '8',
    name: 'Pizza Margherita',
    description: 'Pizza dengan tomat segar, mozzarella, basil, dan olive oil.',
    category: 'Italian',
    price: 55000,
    image: '🍕',
    calories: 800,
    rating: 4.8,
    cookingTime: '25 menit',
  ),
  Food(
    id: '9',
    name: 'Burger Beef Classic',
    description: 'Burger daging sapi dengan keju, lettuce, tomat, dan saus spesial.',
    category: 'Western',
    price: 35000,
    image: '🍔',
    calories: 750,
    rating: 4.7,
    cookingTime: '15 menit',
  ),
  Food(
    id: '10',
    name: 'Pad Thai',
    description: 'Mie Thailand goreng dengan udang, telur, kacang, dan tauge.',
    category: 'Thai',
    price: 32000,
    image: '🍝',
    calories: 520,
    rating: 4.8,
    cookingTime: '20 menit',
  ),
  Food(
    id: '11',
    name: 'Tom Yum Goong',
    description: 'Sup Thailand pedas asam dengan udang, jamur, dan rempah khas.',
    category: 'Thai',
    price: 38000,
    image: '🍲',
    calories: 200,
    rating: 4.6,
    cookingTime: '25 menit',
  ),
  Food(
    id: '12',
    name: 'Es Teh Manis',
    description: 'Teh manis dingin segar yang sempurna untuk menemani makanan.',
    category: 'Drinks',
    price: 5000,
    image: '🧃',
    calories: 120,
    rating: 4.5,
    cookingTime: '5 menit',
  ),
];